version: '3.8'
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: firenewsdb
    ports:
      - "33306:3306"
    volumes:
      - db_data:/var/lib/mysql
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./backend:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./frontend:/app
    command: ["npm", "run", "dev"]
volumes:
  db_data:
