version: '3.8'
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: firenewsdb
    ports:
      - "33306:3306"
    volumes:
      - db_data:/var/lib/mysql
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - mysql
    ports:
      - "9500:9500"
    restart: always
    volumes:
      - ./backend:/app
    command: ["./start.sh"]
  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env
    environment:
      - PORT=3500
    depends_on:
      - backend
    ports:
      - "3500:3500"
    restart: always
    volumes:
      - ./frontend/pages:/app/pages
      - ./frontend/components:/app/components
      - ./frontend/lib:/app/lib
      - ./frontend/styles:/app/styles
      - ./frontend/public:/app/public
    command: ["npm", "run", "dev", "--", "--port", "3500"]
volumes:
  db_data:
