"""create excel_uploads table

Revision ID: 674d25fa57ba
Revises: d1d8596914cd
Create Date: 2025-07-22 11:14:11.358931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '674d25fa57ba'
down_revision: Union[str, Sequence[str], None] = 'd1d8596914cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('excel_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=36), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('from_url', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_excel_uploads_external_id'), 'excel_uploads', ['external_id'], unique=True)
    op.create_index(op.f('ix_excel_uploads_id'), 'excel_uploads', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(op.f('ix_excel_uploads_id'), table_name='excel_uploads')
    op.drop_index(op.f('ix_excel_uploads_external_id'), table_name='excel_uploads')
    op.drop_table('excel_uploads')
    # ### end Alembic commands ###
