"""add_user_roles_and_activity_logs

Revision ID: a878fffa9068
Revises: 4e39582f61fa
Create Date: 2025-07-30 08:24:26.358287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a878fffa9068'
down_revision: Union[str, Sequence[str], None] = '4e39582f61fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fire_news_id'), table_name='fire_news')
    op.drop_table('fire_news')
    op.add_column('users', sa.Column('username', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'first_name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('users', 'phone',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('users', 'city',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('users', 'state',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('users', 'country',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.Enum('USER', 'REPORTER', 'ADMIN', name='userrole'),
               existing_nullable=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'bio')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'province')
    op.drop_column('users', 'profile_image_url')
    op.drop_column('users', 'postal_code')
    op.drop_column('users', 'address')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=False))
    op.add_column('users', sa.Column('address', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('users', sa.Column('postal_code', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('users', sa.Column('profile_image_url', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('users', sa.Column('province', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('users', sa.Column('last_login', mysql.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('bio', mysql.VARCHAR(length=500), nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.alter_column('users', 'role',
               existing_type=sa.Enum('USER', 'REPORTER', 'ADMIN', name='userrole'),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('users', 'country',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('users', 'state',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('users', 'city',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'username')
    op.create_table('fire_news',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('published_date', mysql.DATETIME(), nullable=True),
    sa.Column('url', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('source', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('fire_related_score', mysql.FLOAT(), nullable=True),
    sa.Column('verification_result', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('verified_at', mysql.DATETIME(), nullable=True),
    sa.Column('state', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('province', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('country', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('latitude', mysql.FLOAT(), nullable=True),
    sa.Column('longitude', mysql.FLOAT(), nullable=True),
    sa.Column('image_url', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('tags', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('reporter_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('county', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_fire_news_id'), 'fire_news', ['id'], unique=False)
    # ### end Alembic commands ###
